ALTER DATABASE "railway" OWNER TO postgres;
ALTER ROLE staging_legacy_admin LOGIN SUPERUSER CREATEDB CREATEROLE REPLICATION BYPASSRLS;
GRANT CONNECT ON DATABASE "railway" TO PUBLIC;
GRANT TEMPORARY ON DATABASE "railway" TO PUBLIC;
REVOKE CONNECT ON DATABASE "railway" FROM staging_owner_v2;
REVOKE CONNECT ON DATABASE "railway" FROM staging_controller_v2;
REVOKE CONNECT ON DATABASE "railway" FROM staging_verifier_v2;
REVOKE CONNECT ON DATABASE "railway" FROM postgres;
GRANT USAGE ON SCHEMA public TO PUBLIC;
GRANT USAGE ON TYPE public.agent_availability TO PUBLIC;
GRANT USAGE ON TYPE public.answer_bank TO PUBLIC;
GRANT USAGE ON TYPE public.applied_set TO PUBLIC;
GRANT USAGE ON TYPE public.apply_attempts TO PUBLIC;
GRANT USAGE ON TYPE public.apply_queue TO PUBLIC;
GRANT USAGE ON TYPE public.apply_queue_status TO PUBLIC;
GRANT USAGE ON TYPE public.apply_result_events TO PUBLIC;
GRANT USAGE ON TYPE public.auth_challenge TO PUBLIC;
GRANT USAGE ON TYPE public.autotriage_actions TO PUBLIC;
GRANT USAGE ON TYPE public.command_acks TO PUBLIC;
GRANT USAGE ON TYPE public.compute_queue TO PUBLIC;
GRANT USAGE ON TYPE public.dedup_repair_actions TO PUBLIC;
GRANT USAGE ON TYPE public.discovered_postings TO PUBLIC;
GRANT USAGE ON TYPE public.email_reconcile_actions TO PUBLIC;
GRANT USAGE ON TYPE public.fleet_assets TO PUBLIC;
GRANT USAGE ON TYPE public.fleet_config TO PUBLIC;
GRANT USAGE ON TYPE public.fleet_console_audit TO PUBLIC;
GRANT USAGE ON TYPE public.fleet_decision_policies TO PUBLIC;
GRANT USAGE ON TYPE public.fleet_diagnoses TO PUBLIC;
GRANT USAGE ON TYPE public.fleet_knobs TO PUBLIC;
GRANT USAGE ON TYPE public.fleet_machine_blackout TO PUBLIC;
GRANT USAGE ON TYPE public.fleet_task_status TO PUBLIC;
GRANT USAGE ON TYPE public.fleet_worker_blocklist TO PUBLIC;
GRANT USAGE ON TYPE public.fleet_worker_lease_ledger TO PUBLIC;
GRANT USAGE ON TYPE public.fleet_worker_principals TO PUBLIC;
GRANT USAGE ON TYPE public.inbox_events TO PUBLIC;
GRANT USAGE ON TYPE public.inbox_outcomes TO PUBLIC;
GRANT USAGE ON TYPE public.linkedin_queue TO PUBLIC;
GRANT USAGE ON TYPE public.llm_usage TO PUBLIC;
GRANT USAGE ON TYPE public.otp_request TO PUBLIC;
GRANT USAGE ON TYPE public.poison_jobs TO PUBLIC;
GRANT USAGE ON TYPE public.rate_governor TO PUBLIC;
GRANT USAGE ON TYPE public.remote_commands TO PUBLIC;
GRANT USAGE ON TYPE public.search_tasks TO PUBLIC;
GRANT USAGE ON TYPE public.worker_heartbeat TO PUBLIC;
GRANT USAGE ON TYPE public.workers TO PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT EXECUTE ON FUNCTIONS TO PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT USAGE ON TYPES TO PUBLIC;
DROP FUNCTION IF EXISTS public.fleet_worker_identity();
ALTER TABLE "public"."agent_availability" OWNER TO "postgres";
ALTER TABLE "public"."answer_bank" OWNER TO "postgres";
ALTER TABLE "public"."applied_set" OWNER TO "postgres";
ALTER TABLE "public"."apply_attempts" OWNER TO "postgres";
ALTER TABLE "public"."apply_queue" OWNER TO "postgres";
ALTER TABLE "public"."apply_result_events" OWNER TO "postgres";
ALTER TABLE "public"."auth_challenge" OWNER TO "postgres";
ALTER TABLE "public"."autotriage_actions" OWNER TO "postgres";
ALTER TABLE "public"."command_acks" OWNER TO "postgres";
ALTER TABLE "public"."compute_queue" OWNER TO "postgres";
ALTER TABLE "public"."dedup_repair_actions" OWNER TO "postgres";
ALTER TABLE "public"."discovered_postings" OWNER TO "postgres";
ALTER TABLE "public"."email_reconcile_actions" OWNER TO "postgres";
ALTER TABLE "public"."fleet_assets" OWNER TO "postgres";
ALTER TABLE "public"."fleet_config" OWNER TO "postgres";
ALTER TABLE "public"."fleet_console_audit" OWNER TO "postgres";
ALTER TABLE "public"."fleet_decision_policies" OWNER TO "postgres";
ALTER TABLE "public"."fleet_diagnoses" OWNER TO "postgres";
ALTER TABLE "public"."fleet_knobs" OWNER TO "postgres";
ALTER TABLE "public"."fleet_machine_blackout" OWNER TO "postgres";
ALTER TABLE "public"."fleet_worker_blocklist" OWNER TO "postgres";
ALTER TABLE "public"."fleet_worker_lease_ledger" OWNER TO "postgres";
ALTER TABLE "public"."fleet_worker_principals" OWNER TO "postgres";
ALTER TABLE "public"."inbox_events" OWNER TO "postgres";
ALTER TABLE "public"."inbox_outcomes" OWNER TO "postgres";
ALTER TABLE "public"."linkedin_queue" OWNER TO "postgres";
ALTER TABLE "public"."llm_usage" OWNER TO "postgres";
ALTER TABLE "public"."otp_request" OWNER TO "postgres";
ALTER TABLE "public"."poison_jobs" OWNER TO "postgres";
ALTER TABLE "public"."rate_governor" OWNER TO "postgres";
ALTER TABLE "public"."remote_commands" OWNER TO "postgres";
ALTER TABLE "public"."search_tasks" OWNER TO "postgres";
ALTER TABLE "public"."worker_heartbeat" OWNER TO "postgres";
ALTER TABLE "public"."workers" OWNER TO "postgres";
ALTER SEQUENCE "public"."apply_result_events_id_seq" OWNER TO "postgres";
ALTER SEQUENCE "public"."auth_challenge_id_seq" OWNER TO "postgres";
ALTER SEQUENCE "public"."autotriage_actions_id_seq" OWNER TO "postgres";
ALTER SEQUENCE "public"."dedup_repair_actions_id_seq" OWNER TO "postgres";
ALTER SEQUENCE "public"."discovered_postings_id_seq" OWNER TO "postgres";
ALTER SEQUENCE "public"."email_reconcile_actions_id_seq" OWNER TO "postgres";
ALTER SEQUENCE "public"."fleet_console_audit_id_seq" OWNER TO "postgres";
ALTER SEQUENCE "public"."fleet_diagnoses_id_seq" OWNER TO "postgres";
ALTER SEQUENCE "public"."fleet_knobs_id_seq" OWNER TO "postgres";
ALTER SEQUENCE "public"."fleet_machine_blackout_id_seq" OWNER TO "postgres";
ALTER SEQUENCE "public"."inbox_events_id_seq" OWNER TO "postgres";
ALTER SEQUENCE "public"."llm_usage_id_seq" OWNER TO "postgres";
ALTER SEQUENCE "public"."otp_request_id_seq" OWNER TO "postgres";
ALTER SEQUENCE "public"."remote_commands_id_seq" OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_controller_otp_answer"(p_request_id bigint, p_code text, p_kind text, p_email_ts timestamp with time zone, p_message_id text, p_answered_ttl integer) OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_controller_otp_pending"(p_limit integer) OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_controller_otp_purge"() OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_controller_otp_used_messages"(p_ids text[]) OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_controller_verify_submission"(p_lane text, p_url text, p_evidence_ref text, p_verification_method text) OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_worker_ack_command"(p_command_id bigint, p_worker text) OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_worker_admission_snapshot"() OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_worker_agent_blocks"() OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_worker_attempt_create"(p_route text, p_route_version text, p_evidence jsonb) OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_worker_attempt_transition"(p_attempt uuid, p_expected text, p_state text, p_evidence jsonb) OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_worker_authorize_lease"(p_lane text, p_url text, p_worker text, p_attempt integer) OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_worker_claim_liveness"() OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_worker_complete_compute"(p_url text, p_task text, p_status text, p_result jsonb, p_usage jsonb) OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_worker_complete_search"(p_task_id text, p_postings jsonb, p_error text) OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_worker_evaluate_agent_budget"(p_caps jsonb, p_window_seconds integer, p_cooldown_seconds integer) OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_worker_heartbeat"(p_telemetry jsonb) OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_worker_lease_ats"(p_worker text, p_home_ip text, p_ttl integer, p_sw_version text, p_liveness_fresh integer) OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_worker_lease_compute"() OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_worker_lease_linkedin"(p_worker text, p_public_ip text, p_owner_ip text, p_ttl integer, p_sw_version text) OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_worker_lease_search"() OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_worker_mark_browser_interaction"() OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_worker_otp_consume"(p_request_id bigint) OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_worker_otp_request"(p_worker text, p_job_url text, p_application_url text, p_ttl_seconds integer) OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_worker_otp_wait"(p_request_id bigint) OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_worker_park"(p_lane text, p_url text, p_worker text, p_kind text, p_halt_seconds integer, p_evidence jsonb) OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_worker_park_infrastructure"(p_url text, p_worker text, p_error text) OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_worker_record_agent_wall"(p_agent text, p_blocked_until timestamp with time zone) OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_worker_refund_linkedin_canary"(p_url text, p_worker text, p_attempt integer) OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_worker_requeue"(p_lane text, p_url text, p_worker text, p_error text) OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_worker_runtime_state"(p_worker text) OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_worker_schema_contract"() OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_worker_terminalize"(p_lane text, p_url text, p_worker text, p_status text, p_apply_status text, p_apply_error text, p_evidence jsonb) OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_worker_version_status"(p_worker text, p_reported text) OWNER TO "postgres";
ALTER FUNCTION "public"."fleet_worker_write_liveness"(p_url text, p_status text, p_reason text) OWNER TO "postgres";
ALTER TYPE "public"."apply_queue_status" OWNER TO "postgres";
ALTER TYPE "public"."fleet_task_status" OWNER TO "postgres";
ALTER SCHEMA "public" OWNER TO "pg_database_owner";
REVOKE "staging_owner_v2" FROM "staging_controller_v2";
REVOKE "staging_migrator_v2" FROM "staging_controller_v2";
DROP OWNED BY "staging_controller_v2";
DROP ROLE "staging_controller_v2";
DROP OWNED BY "staging_verifier_v2";
DROP ROLE "staging_verifier_v2";
DROP OWNED BY "staging_migrator_v2";
DROP ROLE "staging_migrator_v2";
DROP OWNED BY "staging_owner_v2";
DROP ROLE "staging_owner_v2";
