ALTER ROLE staging_legacy_admin NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
GRANT TEMPORARY ON DATABASE "railway" TO PUBLIC;
REVOKE CONNECT ON DATABASE "railway" FROM staging_worker_ats_0;
GRANT USAGE ON SCHEMA public TO PUBLIC;
GRANT USAGE ON TYPE public.agent_availability TO PUBLIC;
GRANT USAGE ON TYPE public.answer_bank TO PUBLIC;
GRANT USAGE ON TYPE public.applied_set TO PUBLIC;
GRANT USAGE ON TYPE public.apply_attempts TO PUBLIC;
GRANT USAGE ON TYPE public.apply_queue TO PUBLIC;
GRANT USAGE ON TYPE public.apply_queue_status TO PUBLIC;
GRANT USAGE ON TYPE public.apply_result_events TO PUBLIC;
GRANT USAGE ON TYPE public.auth_challenge TO PUBLIC;
GRANT USAGE ON TYPE public.autotriage_actions TO PUBLIC;
GRANT USAGE ON TYPE public.command_acks TO PUBLIC;
GRANT USAGE ON TYPE public.compute_queue TO PUBLIC;
GRANT USAGE ON TYPE public.dedup_repair_actions TO PUBLIC;
GRANT USAGE ON TYPE public.discovered_postings TO PUBLIC;
GRANT USAGE ON TYPE public.email_reconcile_actions TO PUBLIC;
GRANT USAGE ON TYPE public.fleet_assets TO PUBLIC;
GRANT USAGE ON TYPE public.fleet_config TO PUBLIC;
GRANT USAGE ON TYPE public.fleet_console_audit TO PUBLIC;
GRANT USAGE ON TYPE public.fleet_decision_policies TO PUBLIC;
GRANT USAGE ON TYPE public.fleet_diagnoses TO PUBLIC;
GRANT USAGE ON TYPE public.fleet_knobs TO PUBLIC;
GRANT USAGE ON TYPE public.fleet_machine_blackout TO PUBLIC;
GRANT USAGE ON TYPE public.fleet_task_status TO PUBLIC;
GRANT USAGE ON TYPE public.fleet_worker_blocklist TO PUBLIC;
GRANT USAGE ON TYPE public.fleet_worker_lease_ledger TO PUBLIC;
GRANT USAGE ON TYPE public.fleet_worker_principals TO PUBLIC;
GRANT USAGE ON TYPE public.inbox_events TO PUBLIC;
GRANT USAGE ON TYPE public.inbox_outcomes TO PUBLIC;
GRANT USAGE ON TYPE public.linkedin_queue TO PUBLIC;
GRANT USAGE ON TYPE public.llm_usage TO PUBLIC;
GRANT USAGE ON TYPE public.otp_request TO PUBLIC;
GRANT USAGE ON TYPE public.poison_jobs TO PUBLIC;
GRANT USAGE ON TYPE public.rate_governor TO PUBLIC;
GRANT USAGE ON TYPE public.remote_commands TO PUBLIC;
GRANT USAGE ON TYPE public.search_tasks TO PUBLIC;
GRANT USAGE ON TYPE public.worker_heartbeat TO PUBLIC;
GRANT USAGE ON TYPE public.workers TO PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE staging_controller_v2 GRANT EXECUTE ON FUNCTIONS TO PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE staging_controller_v2 GRANT USAGE ON TYPES TO PUBLIC;
DROP FUNCTION IF EXISTS public.fleet_worker_identity();
DELETE FROM public.fleet_worker_principals WHERE role_name='staging_worker_ats_0';
DROP OWNED BY "staging_worker_ats_0";
DROP ROLE "staging_worker_ats_0";
