# register-discover-score.ps1 [-Unregister]
#
# Owner-run schedule setup for home discovery/enrichment and capped scoring/audit.
# Run from an elevated PowerShell on the home box:
#
#   .\register-discover-score.ps1
#
# Runbook:
# - SLA: discovered -> scored should advance within 48h.
# - Hardware guard: keep triggers between 08:00 and 20:00 local; never move these
#   into unattended overnight hours on the 16GB Dell G15.
# - Done = logs are growing and MAX(discovered_at) / MAX(scored_at) advance.

param(
  [switch]$Unregister
)

$ErrorActionPreference = "Stop"
$repo = $PSScriptRoot
if (-not $repo) { $repo = Split-Path -Parent $MyInvocation.MyCommand.Path }
Set-Location $repo

$TaskPrefix = "ApplyPilot "
$wrapperDir = Join-Path $repo ".fleet-logs\_task-wrappers"
$logDir = Join-Path $repo ".fleet-logs"

$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
  Write-Host "[register-discover-score] NOT elevated. Re-run this script from an Administrator PowerShell." -ForegroundColor Red
  exit 1
}

New-Item -ItemType Directory -Force -Path $wrapperDir | Out-Null
New-Item -ItemType Directory -Force -Path $logDir | Out-Null

function Remove-CadenceTask([string]$Name) {
  $existing = Get-ScheduledTask -TaskName $Name -ErrorAction SilentlyContinue
  if ($existing) {
    Unregister-ScheduledTask -TaskName $Name -Confirm:$false
    Write-Host "  unregistered $Name" -ForegroundColor Yellow
  }
}

function Write-Wrapper([string]$name, [string]$content) {
  $path = Join-Path $wrapperDir "$name.ps1"
  Set-Content -Path $path -Value $content -Encoding UTF8
  return $path
}

function Register-CadenceTask {
  param(
    [Parameter(Mandatory = $true)][string]$Name,
    [Parameter(Mandatory = $true)][string]$WrapperPath,
    [Parameter(Mandatory = $true)]$Trigger,
    [Parameter(Mandatory = $true)]$Settings,
    [string]$Description = ""
  )
  Remove-CadenceTask $Name
  $argument = "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$WrapperPath`""
  $action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument $argument -WorkingDirectory $repo
  $principal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" -LogonType Interactive -RunLevel Limited
  Register-ScheduledTask -TaskName $Name -Action $action -Trigger $Trigger -Settings $Settings `
    -Principal $principal -Description $Description -Force | Out-Null
  Write-Host "  registered $Name -> $WrapperPath" -ForegroundColor Green
}

$discoverName = "${TaskPrefix}DiscoverEnrich"
$scoreName = "${TaskPrefix}ScoreAudit"

if ($Unregister) {
  Remove-CadenceTask $discoverName
  Remove-CadenceTask $scoreName
  Write-Host "[register-discover-score] unregister complete." -ForegroundColor Green
  exit 0
}

$runApplyPilotPs1 = Join-Path $repo "run-applypilot.ps1"
if (-not (Test-Path $runApplyPilotPs1)) { throw "run-applypilot.ps1 not found at $runApplyPilotPs1" }

Write-Host "`n[register-discover-score] registering DiscoverEnrich (09:30 + 15:30)..." -ForegroundColor Cyan
$discoverLog = Join-Path $logDir "discover-enrich.log"
$discoverWrapperContent = @"
# Auto-generated by register-discover-score.ps1 -- do not hand-edit; re-run the register script instead.
`$ErrorActionPreference = 'Continue'
Set-Location '$repo'
`$log = '$discoverLog'
Add-Content -Path `$log -Value ('[' + (Get-Date -Format 'o') + '] === DiscoverEnrich start ===')
& '$runApplyPilotPs1' run discover enrich --workers 1 --discover-mode fast *>> `$log
`$code = `$LASTEXITCODE
Add-Content -Path `$log -Value ('[' + (Get-Date -Format 'o') + '] discover-enrich exit=' + `$code)
exit `$code
"@
$discoverWrapper = Write-Wrapper "discover-enrich-task" $discoverWrapperContent
$discoverTriggers = @(
  New-ScheduledTaskTrigger -Daily -At "09:30",
  New-ScheduledTaskTrigger -Daily -At "15:30"
)
$discoverSettings = New-ScheduledTaskSettingsSet -MultipleInstances IgnoreNew `
  -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -ExecutionTimeLimit (New-TimeSpan -Hours 3)
Register-CadenceTask -Name "${TaskPrefix}DiscoverEnrich" -WrapperPath $discoverWrapper -Trigger $discoverTriggers -Settings $discoverSettings `
  -Description "ApplyPilot home discovery/enrichment: owner-present daytime cadence, workers=1, fast discovery mode."

Write-Host "`n[register-discover-score] registering ScoreAudit (12:30 + 18:30)..." -ForegroundColor Cyan
$scoreLog = Join-Path $logDir "score-audit.log"
$scoreWrapperContent = @"
# Auto-generated by register-discover-score.ps1 -- do not hand-edit; re-run the register script instead.
`$ErrorActionPreference = 'Continue'
Set-Location '$repo'
`$log = '$scoreLog'
Add-Content -Path `$log -Value ('[' + (Get-Date -Format 'o') + '] === ScoreAudit start ===')
& '$runApplyPilotPs1' score-jobs --limit 400 --workers 1 *>> `$log
`$scoreCode = `$LASTEXITCODE
Add-Content -Path `$log -Value ('[' + (Get-Date -Format 'o') + '] score-jobs exit=' + `$scoreCode)
if (`$scoreCode -eq 0) {
  & '$runApplyPilotPs1' run audit *>> `$log
  `$auditCode = `$LASTEXITCODE
  Add-Content -Path `$log -Value ('[' + (Get-Date -Format 'o') + '] audit exit=' + `$auditCode)
  exit `$auditCode
}
exit `$scoreCode
"@
$scoreWrapper = Write-Wrapper "score-audit-task" $scoreWrapperContent
$scoreTriggers = @(
  New-ScheduledTaskTrigger -Daily -At "12:30",
  New-ScheduledTaskTrigger -Daily -At "18:30"
)
$scoreSettings = New-ScheduledTaskSettingsSet -MultipleInstances IgnoreNew `
  -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -ExecutionTimeLimit (New-TimeSpan -Hours 2)
Register-CadenceTask -Name "${TaskPrefix}ScoreAudit" -WrapperPath $scoreWrapper -Trigger $scoreTriggers -Settings $scoreSettings `
  -Description "ApplyPilot capped home scoring/audit: score cap 400, workers=1, owner-present daytime cadence."

Write-Host "`n=================================================================================" -ForegroundColor Cyan
Write-Host " Done = " -ForegroundColor Cyan -NoNewline
Write-Host "verify these once the tasks have had a chance to run:" -ForegroundColor Cyan
Write-Host "=================================================================================" -ForegroundColor Cyan
Write-Host "  [ ] .fleet-logs\discover-enrich.log and score-audit.log are growing"
Write-Host "  [ ] MAX(discovered_at) and MAX(scored_at) are advancing"
Write-Host "  [ ] Discovered-to-scored SLA is <= 48h"
Write-Host "  [ ] Get-ScheduledTask -TaskName 'ApplyPilot DiscoverEnrich','ApplyPilot ScoreAudit' shows LastTaskResult=0"
Write-Host "`n[register-discover-score] wrapper scripts live under $wrapperDir (regenerated on every run)." -ForegroundColor Cyan
Write-Host "[register-discover-score] registration complete." -ForegroundColor Green
