"""Canonical ATS sender domains and provider-domain equivalence groups."""

ATS_SENDER_DOMAINS: frozenset[str] = frozenset(
    {
        "greenhouse.io",
        "greenhouse-mail.io",
        "lever.co",
        "hire.lever.co",
        "workday.com",
        "myworkdayjobs.com",
        "myworkday.com",
        "icims.com",
        "brassring.com",
        "smartrecruiters.com",
        "smartrecruiters-mail.com",
        "workable.com",
        "workablemail.com",
        "taleo.net",
        "jobvite.com",
        "jobvite-mail.com",
        "recruitee.com",
        "ashbyhq.com",
        "ashbyhq-mail.com",
        "ashby.email",
        "successfactors.com",
        "applytojob.com",
        "bamboohr.com",
        "rippling.com",
        "eightfold.ai",
        "beamery.com",
        "paradox.ai",
        "fountain.com",
        "dover.com",
        "dover.io",
        "teamtailor.com",
        "teamtailor-mail.com",
        "pinpointhq.com",
        "comeet.co",
        "gem.com",
        "breezy.hr",
        "hiringthing.com",
    }
)

PROVIDER_DOMAIN_GROUPS: tuple[tuple[str, ...], ...] = (
    ("oraclecloud.com", "oracle.com", "taleo.net"),
    (
        "myworkday.com",
        "myworkdayjobs.com",
        "myworkdaysite.com",
        "workdayjobs.com",
        "workday.com",
    ),
    ("greenhouse.io", "greenhouse-mail.io"),
    ("adp.com", "workforcenow.adp.com"),
    ("amazon.jobs", "jobs.amazon.com"),
    ("eightfold.ai",),
    ("smartrecruiters.com", "smartrecruiters-mail.com"),
    ("workable.com", "workablemail.com"),
    ("ashbyhq.com", "ashbyhq-mail.com", "ashby.email"),
    ("jobvite.com", "jobvite-mail.com"),
    ("teamtailor.com", "teamtailor-mail.com"),
)
